image: microsoft/dotnet:latest

stages:
  - build
  - publish

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

publish:
  stage: publish
  script:
    - dotnet build
    - dotnet publish
    - dotnet nuget push Microsoft.HBase.Client/bin/Debug/*.nupkg -k $NUGET_KEY -s https://www.myget.org/F/s2/api/v2/package

